name: 'New release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for new release.'
        type: string
        required: true

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: 'Draft new release'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup Repository (${{github.event.repository.name}})'
        uses: actions/checkout@v4
      
      - name: 'Create new release'
        uses: ncipollo/release-action@v1
        
